"""update task_table

Revision ID: 11978ed75d72
Revises: 02f4c04f7cd9
Create Date: 2026-02-10 18:11:25.381410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11978ed75d72'
down_revision: Union[str, Sequence[str], None] = '02f4c04f7cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spiderbuilder',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_platform', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='资源平台'),
    sa.Column('form_rule', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='表单生成规则'),
    sa.Column('crawl_rule', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='抓取逻辑规则'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spiderbuilder_source_platform'), 'spiderbuilder', ['source_platform'], unique=True)
    op.create_table('task',
    sa.Column('task_group', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False, comment='任务分组'),
    sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False, comment='任务名称'),
    sa.Column('task_content', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='任务表单内容'),
    sa.Column('source_platform', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='资源平台'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('status', sa.SMALLINT(), nullable=False, comment='任务状态'),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_source_platform'), 'task', ['source_platform'], unique=False)
    op.create_index(op.f('ix_task_task_fingerprint'), 'task', ['task_fingerprint'], unique=True)
    op.create_index(op.f('ix_task_task_group'), 'task', ['task_group'], unique=False)
    op.create_index(op.f('ix_task_task_name'), 'task', ['task_name'], unique=False)
    op.create_index(op.f('ix_task_user_id'), 'task', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_user_id'), table_name='task')
    op.drop_index(op.f('ix_task_task_name'), table_name='task')
    op.drop_index(op.f('ix_task_task_group'), table_name='task')
    op.drop_index(op.f('ix_task_task_fingerprint'), table_name='task')
    op.drop_index(op.f('ix_task_source_platform'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_spiderbuilder_source_platform'), table_name='spiderbuilder')
    op.drop_table('spiderbuilder')
    # ### end Alembic commands ###
