"""update data table

Revision ID: 1742e844e84c
Revises: 239c45bc9028
Create Date: 2026-02-12 14:21:50.144743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1742e844e84c'
down_revision: Union[str, Sequence[str], None] = '239c45bc9028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_query_config', 'db_uri',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_comment='数据连接')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_query_config', 'db_uri',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_comment='数据连接')
    # ### end Alembic commands ###
