"""update rule table

Revision ID: 22d4a4efb5da
Revises: 11978ed75d72
Create Date: 2026-02-10 18:14:37.602796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22d4a4efb5da'
down_revision: Union[str, Sequence[str], None] = '11978ed75d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_platform', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='资源平台'),
    sa.Column('form_rule', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='表单生成规则'),
    sa.Column('crawl_rule', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='抓取逻辑规则'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_source_platform'), 'rule', ['source_platform'], unique=True)
    op.drop_index(op.f('ix_spiderbuilder_source_platform'), table_name='spiderbuilder')
    op.drop_table('spiderbuilder')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spiderbuilder',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='资源平台'),
    sa.Column('form_rule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='表单生成规则'),
    sa.Column('crawl_rule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='抓取逻辑规则'),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('spiderbuilder_pkey'))
    )
    op.create_index(op.f('ix_spiderbuilder_source_platform'), 'spiderbuilder', ['source_platform'], unique=True)
    op.drop_index(op.f('ix_rule_source_platform'), table_name='rule')
    op.drop_table('rule')
    # ### end Alembic commands ###
