"""update data table

Revision ID: 239c45bc9028
Revises: fb99d6c748dc
Create Date: 2026-02-12 14:13:42.359479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '239c45bc9028'
down_revision: Union[str, Sequence[str], None] = 'fb99d6c748dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_query',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='名称'),
    sa.Column('sql', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False, comment='SQL 查询'),
    sa.Column('config_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_query_name'), 'data_query', ['name'], unique=True)
    op.create_table('data_query_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='名称'),
    sa.Column('db_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='数据库'),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='数据表'),
    sa.Column('db_uri', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False, comment='数据连接'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_query_config_name'), 'data_query_config', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_query_config_name'), table_name='data_query_config')
    op.drop_table('data_query_config')
    op.drop_index(op.f('ix_data_query_name'), table_name='data_query')
    op.drop_table('data_query')
    # ### end Alembic commands ###
