"""update rule table

Revision ID: 2f22a303f739
Revises: 22d4a4efb5da
Create Date: 2026-02-10 18:37:07.617633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f22a303f739'
down_revision: Union[str, Sequence[str], None] = '22d4a4efb5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskrun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('source_platform', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='资源平台'),
    sa.Column('priority', sa.SMALLINT(), nullable=False, comment='任务优先级 数字越大越高'),
    sa.Column('cron_expr', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False, comment='CRON定时器'),
    sa.Column('crawl_task', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='抓取任务'),
    sa.Column('status', sa.SMALLINT(), nullable=False, comment='抓取任务状态'),
    sa.Column('error_reason', sa.TEXT(), nullable=False, comment='抓取任务异常原因'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskrun_source_platform'), 'taskrun', ['source_platform'], unique=False)
    op.create_index(op.f('ix_taskrun_task_fingerprint'), 'taskrun', ['task_fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskrun_task_fingerprint'), table_name='taskrun')
    op.drop_index(op.f('ix_taskrun_source_platform'), table_name='taskrun')
    op.drop_table('taskrun')
    # ### end Alembic commands ###
