"""add_task_table

Revision ID: 34211bac2fde
Revises: e5d5fed02b3b
Create Date: 2026-02-09 14:42:42.917885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34211bac2fde'
down_revision: Union[str, Sequence[str], None] = 'e5d5fed02b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('task_group', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('task_content', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='任务详情内容'),
    sa.Column('source_platform', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sa.SMALLINT(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_source_platform'), 'task', ['source_platform'], unique=False)
    op.create_index(op.f('ix_task_task_fingerprint'), 'task', ['task_fingerprint'], unique=True)
    op.create_index(op.f('ix_task_task_group'), 'task', ['task_group'], unique=False)
    op.create_index(op.f('ix_task_user'), 'task', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_user'), table_name='task')
    op.drop_index(op.f('ix_task_task_group'), table_name='task')
    op.drop_index(op.f('ix_task_task_fingerprint'), table_name='task')
    op.drop_index(op.f('ix_task_source_platform'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
