"""update task_table

Revision ID: 8166103f6660
Revises: ff0ff8307a7e
Create Date: 2026-02-09 14:57:38.863531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '8166103f6660'
down_revision: Union[str, Sequence[str], None] = 'ff0ff8307a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status',
               existing_type=sa.SMALLINT(),
               comment='任务状态',
               existing_comment='资源平台',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status',
               existing_type=sa.SMALLINT(),
               comment='资源平台',
               existing_comment='任务状态',
               existing_nullable=False)
    # ### end Alembic commands ###
