"""update task_table

Revision ID: ba25d942b9f1
Revises: c409b00ad89b
Create Date: 2026-02-09 18:12:05.958950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ba25d942b9f1'
down_revision: Union[str, Sequence[str], None] = 'c409b00ad89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False, comment='任务名称'))
    op.create_index(op.f('ix_task_task_name'), 'task', ['task_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_task_name'), table_name='task')
    op.drop_column('task', 'task_name')
    # ### end Alembic commands ###
