"""update task_table

Revision ID: c409b00ad89b
Revises: 8166103f6660
Create Date: 2026-02-09 17:30:16.739246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c409b00ad89b'
down_revision: Union[str, Sequence[str], None] = '8166103f6660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_task_user'), table_name='task')
    op.create_index(op.f('ix_task_user_id'), 'task', ['user_id'], unique=False)
    op.drop_constraint(op.f('task_user_fkey'), 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    op.drop_column('task', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(op.f('task_user_fkey'), 'task', 'user', ['user'], ['id'])
    op.drop_index(op.f('ix_task_user_id'), table_name='task')
    op.create_index(op.f('ix_task_user'), 'task', ['user'], unique=False)
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###
