"""update rule table

Revision ID: fed7f9fe527f
Revises: 2f22a303f739
Create Date: 2026-02-10 19:19:42.294567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fed7f9fe527f'
down_revision: Union[str, Sequence[str], None] = '2f22a303f739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taskrun', 'error_reason',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='抓取任务异常原因')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taskrun', 'error_reason',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='抓取任务异常原因')
    # ### end Alembic commands ###
