"""add_task_table

Revision ID: ff0ff8307a7e
Revises: 34211bac2fde
Create Date: 2026-02-09 14:54:44.756623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff0ff8307a7e'
down_revision: Union[str, Sequence[str], None] = '34211bac2fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'task_group',
               existing_type=sa.VARCHAR(length=100),
               comment='任务分组',
               existing_nullable=False)
    op.alter_column('task', 'task_content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='任务表单内容',
               existing_comment='任务详情内容',
               existing_nullable=False)
    op.alter_column('task', 'source_platform',
               existing_type=sa.VARCHAR(length=50),
               comment='资源平台',
               existing_nullable=False)
    op.alter_column('task', 'status',
               existing_type=sa.SMALLINT(),
               comment='资源平台',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='资源平台',
               existing_nullable=False)
    op.alter_column('task', 'source_platform',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='资源平台',
               existing_nullable=False)
    op.alter_column('task', 'task_content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='任务详情内容',
               existing_comment='任务表单内容',
               existing_nullable=False)
    op.alter_column('task', 'task_group',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='任务分组',
               existing_nullable=False)
    # ### end Alembic commands ###
